version: '3.8'

services:
  fastapi_app:
    build:
      context: ./
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./credentials/bucket_credential.json:/app/credentials/bucket_credential.json:ro
    networks:
      - my_network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 1s
      retries: 5
networks:
  my_network:
    driver: bridge