version: '3.8'

services:
  fastapi_app:
    build:
      context: ./
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres_db
      - weaviate_db
    networks:
      - my_network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 1s
      retries: 5

  postgres_db:
    image: postgres:15-alpine
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=lio
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 2s
      retries: 5

  weaviate_db:
    image: semitechnologies/weaviate:1.30.15
    container_name: weaviate_db
    ports:
      - "8080:8080"
      - "50051:50051"
    env_file:
      - .env.weaviate
    volumes:
      - weaviate_data:/var/lib/weaviate
    networks:
      - my_network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/meta"]
      interval: 10s
      timeout: 2s
      retries: 5


# 네트워크 정의
networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
  weaviate_data:
